systemd service for worker's ssh server, implement wait online

diff --git a/scripts/cloudrun-worker b/scripts/cloudrun-worker
--- a/scripts/cloudrun-worker
+++ b/scripts/cloudrun-worker
@@ -8,22 +8,23 @@ RW_TMP_DIR="$WORK_DIR/tmp"
 
 ssh-keygen -A -f /etc/cloudrun/override
 
-function host-network-up () {
+function host-network-up () (
     set -e
     ip link add name cloudrun-int type bridge
     ip link set cloudrun-int up
     ip address add 172.30.30.1/30 dev cloudrun-int
-}
+)
 
-function host-network-down () {
+function host-network-down () (
     ip link set cloudrun-int down
     ip link delete cloudrun-int type bridge
-}
+)
 
-function generate-configs () {
+function generate-configs () (
     set -e
     sed -E 's/^([^:]*).*/\1:!!:17752::::::/' < "$RO_DIR"/etc/passwd > "$ROOT_DIR"/etc/shadow
-}
+)
+
 function cleanup () {
     lxc-stop -n cloudrun -P /etc/cloudrun/lxc -k
     umount "$ROOT_DIR"
@@ -51,7 +52,8 @@ fi
 
 echo "Mounting cloudrun-fs"
 ulimit -n 102400
-cloudrun-fs "$FS_META_FILE" "$HASH_STORE_DIR" "$PRIVATE_STORE_DIR" "$FILE_SERVER" "$RO_DIR"
+cloudrun-fs "$FS_META_FILE" "$HASH_STORE_DIR" "$PRIVATE_STORE_DIR" "$FILE_SERVER" "$RO_DIR"&
+sleep 4
 if [ $? -ne 0 ]; then
     echo "ERROR: Unable to mount cloudrun-fs"
     exit
@@ -77,6 +79,22 @@ if [ $? -ne 0 ]; then
     echo "ERROR: Unable to start the container"
     exit
 fi
+
+function waitonline () {
+    while ! timeout 0.5 bash -c "echo > /dev/tcp/172.30.30.2/22022"; do
+        sleep 0.5
+    done
+}
+
+export -f waitonline
+
+echo "Waiting for sshd to start"
+timeout 10 bash -c "waitonline" > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+    echo "ERROR: Unable to start ssh server"
+    exit
+fi
+
 echo "Worker started"
 
 read
